name = "BetweennessCentralityResilience"
uuid = "56a97a59-ae56-414d-9261-5c7360e883d4"
version = "0.0.1"
authors = ["Matt Bhagat-Conway <mwbc@unc.edu>"]

[deps]
ArchGDAL = "c9ce4bd3-c3d5-55b8-8973-c0e20141b8c3"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
GeoDataFrames = "62cb38b5-d8d2-4862-a48e-6a340996859f"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
MetaGraphsNext = "fa8bd995-216d-47f1-8a91-f3b68fbeb377"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
ArchGDAL = "0.10.4"
DataFrames = "1.8.1"
